In [2]:
# Q - Learning example
import numpy as np
import random

In [9]:
# initialize r and q
r = np.array([[-1, -1, -1, -1, 0, -1], [-1, -1, -1, 0, -1, 100], [-1, -1, -1, 0, -1, -1], [-1, 0, 0, -1, 0, -1],
              [0, -1, -1, 0, -1, 100], [-1, 0, -1, -1, 0, 100]])
print('initial r = ',r)

q = np.zeros([6,6],dtype=np.float32)

print('initial q = ',q)

gamma = 0.8           # learning rate

step = 0
while step < 1000:
    state = random.randint(0,5)         #choose the initial state randomly in (0 1 2 3 4 5)
    if state != 5:
        next_state_list=[]
        for i in range(6):
            if r[state,i] != -1:
                next_state_list.append(i)
        next_state = next_state_list[random.randint(0,len(next_state_list)-1)]  #randomly choose the next state and update the reward
        qval = r[state,next_state] + gamma * max(q[next_state])
        q[state,next_state] = qval
    step += 1

print('After recurrance, the final q is: ')
print(q)

# verification
for i in range(5):
    print()
    print("the {} time verifying".format(i + 1))
    state = random.randint(0, 5)
    print('the robot is in {}'.format(state))
    count = 0
    while state != 5:
        if count > 10:
            print('fail')
            break
        # choose the maximum q_max
        q_max = q[state].max()

        q_max_action = []
        for action in range(6):
            if q[state, action] == q_max:
                q_max_action.append(action)

        next_state = q_max_action[random.randint(0, len(q_max_action) - 1)]
        print("the robot goes to " + str(next_state) + '.')
        state = next_state
        count += 1

initial r =  [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [  0  -1  -1   0  -1 100]
 [ -1   0  -1  -1   0 100]]
initial q =  [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
After recurrance, the final q is: 
[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [ 64.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.    0.    0.    0. ]]

the 1 time verifying
the robot is in 1
the robot goes to 5.

the 2 time verifying
the robot is in 5

the 3 time verifying
the robot is in 2
the robot goes to 3.
the robot goes to 1.
the robot goes to 5.

the 4 time verifying
the robot is in 1
the robot goes to 5.

the 5 time verifying
the robot is in 4
the robot goes to 5.


In [ ]:
# DQL 待补充